import { Profile, Chat } from './types';

export const DAILY_FREE_SWIPES = 30;
export const VIP_PRICE = "R$ 9,90";

export const MOCK_PROFILES: Profile[] = [
  {
    id: '1',
    name: 'Júlia',
    age: 23,
    bio: 'Viciada em séries e viagens ✈️. Procurando alguém para dividir uma pizza.',
    imageUrl: '',
    photos: [],
    distance: 2,
    verified: true,
  },
  {
    id: '2',
    name: 'Mariana',
    age: 25,
    bio: 'Arquitetura 📐 | Coffee lover ☕ | Crossfit',
    imageUrl: '',
    photos: [],
    distance: 5,
    verified: false,
  },
  {
    id: '3',
    name: 'Beatriz',
    age: 22,
    bio: 'A vida é muito curta para não comer sobremesa primeiro.',
    imageUrl: '',
    photos: [],
    distance: 12,
    verified: true,
  },
  {
    id: '4',
    name: 'Larissa',
    age: 24,
    bio: 'Gamer 🎮 e mãe de pet 🐶',
    imageUrl: '',
    photos: [],
    distance: 8,
    verified: true,
  },
  {
    id: '5',
    name: 'Carolina',
    age: 26,
    bio: 'Sempre pronta para uma aventura na praia 🌊',
    imageUrl: '',
    photos: [],
    distance: 15,
    verified: false,
  },
];

export const MOCK_CHATS: Chat[] = [
  {
    id: '1',
    name: 'Sofia',
    imageUrl: '',
    lastMessage: 'Vocês deram match!',
    timestamp: 'Agora',
    unreadCount: 0,
    conversationId: 'mock_1',
    otherUserId: 'mock_user_1',
  },
  {
    id: '2',
    name: 'Lucas',
    imageUrl: '',
    lastMessage: 'Vocês deram match!',
    timestamp: 'Agora',
    unreadCount: 0,
    conversationId: 'mock_2',
    otherUserId: 'mock_user_2',
  },
  {
    id: '3',
    name: 'Camila',
    imageUrl: '',
    lastMessage: 'Oi! Tudo bem? Vi que você também curte...',
    timestamp: '14:30',
    unreadCount: 2,
    conversationId: 'mock_3',
    otherUserId: 'mock_user_3',
  },
  {
    id: '4',
    name: 'Rodrigo',
    imageUrl: '',
    lastMessage: 'Haha, ótima foto de perfil. Onde foi?',
    timestamp: 'Ontem',
    unreadCount: 0,
    conversationId: 'mock_4',
    otherUserId: 'mock_user_4',
  },
  {
    id: '5',
    name: 'Juliana',
    imageUrl: '',
    lastMessage: 'Você: Vamos combinar algo então!',
    timestamp: 'Sexta',
    unreadCount: 0,
    conversationId: 'mock_5',
    otherUserId: 'mock_user_5',
  }
];